hashicorp/terraform-exec

- go.mod
- go.sum
The go-getter dependency only compiles on Go versions 1.13 and above, as of v1.4.1. If we want this library to be usable in Go 1.12 projects, we should merge this PR. 
The bug fixed in v1.4.1 of go-getter concerns only HTTP servers that do not return `Content-Length`, and getter requests that do not use `checksum`, neither of which affects tfexec/tfinstall.
> downgrade go-getter to 1.4.0

- tfexec/terraform.go
`Import()` had been missed out of the public API by mistake. Currently we only test the `*Cmd` versions of these functions, so until #19 is implemented this will remain untested.
> implement Import

- .circleci/config.yml
- scripts/release/changelog_links.sh
- scripts/release/release.sh
fixes #11 
Based on the SDK CircleCI setup.
On each PR, a matrix of builds is run:
- build and test with Go 1.12
- build and test with Go 1.14
- gofmt and go vet checks (Go 1.14)
- build and test on Windows
There is a macOS executor on CircleCI, but it doesn't have Go installed, and the architecture is sufficiently similar to Linux to leave this out for now. If we want to test all PRs on macOS we can add this later.
As in the SDK, to release from `master` one needs only to update CHANGELOG.md to include a `#x.y.z (Unreleased)` line and then trigger the `trigger_release` build.
The release workflow will then:
- run all build and test jobs as above
- format the changelog
- modify the version in `tfinstall/version.go` (this will be removed in …
> CI and release process

- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/destroy.go
- tfexec/destroy_test.go
- tfexec/import.go
- tfexec/import_test.go
- tfexec/init.go
- tfexec/init_test.go
- tfexec/output.go
- tfexec/output_test.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/providers_schema.go
- tfexec/providers_schema_test.go
- tfexec/show.go
- tfexec/show_test.go
- tfexec/terraform_test.go
We should only export the methods that execute commands to force all compatibility needs through the controlled interfaces (options, etc), as opposed to letting consumers further customize things like environment. This defeats the purpose of having a canonical testing interface for programmatic CLI invocation.
(per the RFC discussion)
This is based on #23
> Stop exporting exec.Cmd versions of methods

- tfexec/terraform_test.go
Fix a flaky test that would sometimes fail because `exec.Cmd.Env` does not have a stable order.
> fix test: sort env strings

- .circleci/config.yml
Install Go 1.14.6 on Windows build agents.
> CI: install Go 1.14 on Windows

- tfexec/destroy.go
- tfexec/destroy_test.go
- tfexec/errors.go
- tfexec/terraform.go
- tfexec/terraform_cmd.go
- tfexec/terraform_test.go
This is a WIP to modify env var handling slightly and add support for TF_LOG_PATH to tfexec. Unsure if this fulfills the existing use case yet, but just putting this up for further discussion in the meantime.
> Env Var handling and TF_LOG_PATH support

- tfexec/apply.go
- tfexec/destroy.go
- tfexec/e2etest/errors_test.go
- tfexec/errors.go
- tfexec/import.go
- tfexec/init.go
- tfexec/output.go
- tfexec/plan.go
- tfexec/providers_schema.go
- tfexec/show.go
- tfexec/terraform.go
- tfexec/version.go
Note, this is a PR to the `end-to-end-testing` branch, but that can merge first if preferred.
> Clean up error handling for non-ExitError cases

- tfexec/version.go
- tfinstall/tfinstall.go
Releasing v0.5.0 failed because it's the first time the tests have been run since Core 0.13 GA, and they revealed a bug (fixed in https://github.com/hashicorp/terraform/pull/25811) in which the order of the "version" and "outdated" lines in the output of `terraform version` is reversed.
This applies to the following versions:
`0.13.0-beta2`
`0.13.0-beta3`
`0.13.0-rc1`
`0.13.0`
Given this bug in extant versions, I think we should just tolerate the different output order. It's a reasonable assumption that `terraform version` won't output anything else matching the version output regex.
> tolerate reversed version output

- .circleci/config.yml
- tfexec/errors.go
- tfexec/internal/e2etest/apply_test.go
- tfexec/internal/e2etest/destroy_test.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/import_test.go
- tfexec/internal/e2etest/init_test.go
- tfexec/internal/e2etest/output_test.go
- tfexec/internal/e2etest/plan_test.go
- tfexec/internal/e2etest/providers_schema_test.go
- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/internal/e2etest/version_test.go
- tfexec/internal/testutil/tfcache.go
In addition to TF version matrix updates, added go 1.15, changed 1.12 and 1.13 to building only (not testing). Testing only in 1.14 and 1.15 as they are the support Go versions currently.
> Add better version matrix handling and additional version testing for all e2e tests

- tfexec/apply.go
- tfexec/cmd.go
- tfexec/destroy.go
- tfexec/import.go
- tfexec/init.go
- tfexec/internal/e2etest/util_test.go
- tfexec/output.go
- tfexec/plan.go
- tfexec/providers_schema.go
- tfexec/show.go
- tfexec/terraform.go
- tfexec/version.go
I also added `t.Log` calls for stdout/err in tests for better debugging:
```
=== RUN   TestProvidersSchema/1_empty_with_tf_file/empty_with_tf_file-0.13.0
util_test.go:72: CLI Output:
Initializing the backend...
Initializing provider plugins...
Terraform has been successfully initialized!
{"format_version":"0.1"}
--- PASS: TestProvidersSchema (41.31s)
```
This is based on #48
> tee stdout and stderr for consumers

- tfexec/destroy.go
- tfexec/destroy_test.go
- tfexec/init.go
- tfexec/init_test.go
- tfexec/options.go
- tfexec/plan.go
- tfexec/plan_test.go
`init`, `destroy`, and `plan` all have a single optional `[DIR]` positional arg, e.g.:
```
❤ @up ➜  ~  terraform -help init   
Usage: terraform init [options] [DIR]
```
> implement [DIR] positional arg

- tfexec/internal/e2etest/refresh_test.go
- tfexec/options.go
- tfexec/refresh.go
- tfexec/refresh_test.go
Implement `terraform refresh` and all opts.
> implement Refresh

- tfexec/internal/e2etest/util_test.go
- tfexec/terraform.go
This sets the logger to e2etests (and relaxes the logger requirements to not be a struct, but an interface).
> Relax logger interface, log testing CLI command

- tfexec/cmd.go
- tfexec/errors.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/testdata/var/main.tf
- tfexec/internal/e2etest/util_test.go
This only tests plans, I assumed the error strings were the same, but probably wouldn't hurt to add an apply test as well.
I also resolved a minor issue where erroring commands were not in the test logging.
> Add error for missing variable

- CHANGELOG.md
- scripts/release/changelog_links.sh
* Generate issue/PR links to this repository in `CHANGELOG.md`: `hashicorp/terraform-plugin-sdk` -> `hashicorp/terraform-exec`
* Correct existing links in `CHANGELOG.md`
> Correct the linked-to repository in CHANGELOG

- tfexec/errors.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/plan_test.go
- tfexec/options.go
- tfexec/plan.go
- tfexec/plan_test.go
This adds the `-detailed-exitcode` option to `tfexec.Plan()` and returns
a boolean detailing whether a plan diff is empty or non-empty.
This allows the caller to make decisions when the plan has changes.
```
hasChanges, err := tf.Plan(context.Background())
if err != nil {
panic(err)
}
if hasChanges {
// Do something when the plan has changes.
}
```
> Add -detailed-exitcode option to Plan

- go.mod
- internal/version/version.go
- scripts/release/release.sh
- tfexec/cmd.go
- tfexec/cmd_test.go
- tfexec/errors.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/terraform.go
- tfinstall/http.go
- tfinstall/tfinstall.go
- tfinstall/version.go
> Add management of TF_APPEND_USER_AGENT

- tfexec/errors.go
- tfexec/internal/e2etest/workspace_test.go
When calling `terraform workspace new <name>` to create a workspace that already exists, an error is returned. Add support for handling this error.
> Add parsing for workspace already exists error

- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/cmd.go
- tfexec/destroy.go
- tfexec/destroy_test.go
- tfexec/import.go
- tfexec/import_test.go
- tfexec/init.go
- tfexec/init_test.go
- tfexec/options.go
- tfexec/output.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/providers_schema.go
- tfexec/refresh.go
- tfexec/refresh_test.go
- tfexec/show.go
- tfexec/show_test.go
- tfexec/terraform.go
- tfexec/terraform_test.go
- tfexec/version.go
- tfexec/workspace_list.go
- tfexec/workspace_new.go
- tfexec/workspace_select.go
Binary testing reattach functionality requires the `TF_PROVIDERS_REATTACH` env var to be present in the environment in which the Terraform CLI is run. In normal usage, such as in terraform-plugin-test, the value of this env var will change during the lifetime of a `*Terraform`. We therefore provide a way of setting the reattach info string on every relevant Terraform CLI command as if it is an option.
> add ReattachOption

- tfexec/internal/e2etest/util_test.go
- tfexec/internal/testutil/tfcache.go
- tfinstall/download.go
- tfinstall/exact_version.go
- tfinstall/http.go
- tfinstall/latest_version.go
Since we are starting to download a ton of terraform binaries in automation, I wanted to make sure we are appropriately flagging those downloads as part of our automation.
> Set user agent appends for tests

- tfexec/show.go
- tfexec/show_test.go
The SDK used a non-JSON version of ShowPlanFile to return the
human-friendly, opaque-to-machines plan output during testing. With the
switch to tfexec, this is no longer possible, as all `terraform show`
commands have the `-json` flag applied, meaning all output will be JSON
output.
This adds a new function, `ShowRawPlanFile`, which returns a string of
the output of `terraform show` _without_ the `-json` flag, showing the
raw contents of the plan file. A new function was chosen to avoid
overloading the existing ShowPlanFile, and because the existing
ShowPlanFile returns a `tfjson.Plan` type, which we can't shoehorn a
non-JSON return type into easily. Rather than complicate the return
type, it felt like a new function was a better solution.
> Add ShowPlanFileRaw

- tfexec/errors.go
- tfexec/fmt.go
- tfexec/internal/e2etest/fmt_test.go
- tfexec/internal/e2etest/testdata/unformatted/file1.golden.txt
- tfexec/internal/e2etest/testdata/unformatted/file1.tf
- tfexec/internal/e2etest/testdata/unformatted/file2.golden.txt
- tfexec/internal/e2etest/testdata/unformatted/file2.tf
- tfexec/internal/e2etest/util_test.go
- tfexec/options.go
Added 3 functions for formatting support
- `FormatString` for formatting a single string, operates `terraform fmt` in stdin mode
- `FormatCheck` calls `terraform fmt -check` in the working directory, or selected directory, and returns true if the files were already formatted, no files will be written.
- `FormatWrite` calls `terraform fmt` in the working directory, or selected directory, files will be written.
> terraform fmt support

- tfexec/internal/e2etest/show_test.go
- tfinstall/git_ref.go
Commit messages should be self-explanatory.
> Fix failing tests

- tfexec/errors.go
- tfexec/fmt.go
- tfexec/fmt_test.go
- tfexec/version.go
This is mostly a UX enhancement which is already built into LS, so this is to help ease the transition.
> fmt: Gate formatting command on 0.7.7

- tfexec/internal/e2etest/testdata/pre_011_syntax/file1.golden.txt
- tfexec/internal/e2etest/testdata/pre_011_syntax/file1.tf
- tfexec/internal/e2etest/testdata/pre_011_syntax/file2.golden.txt
- tfexec/internal/e2etest/testdata/pre_011_syntax/file2.tf
- tfexec/internal/e2etest/upgrade012_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/options.go
- tfexec/upgrade012.go
- tfexec/upgrade012_test.go
Adds support for the `terraform 0.12upgrade` command
> Adds support for the terraform 0.12upgrade command

- tfexec/errors.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/testdata/var/main.tf
An issue currently exists when a terraform variable with a very long name has no value. In these cases, the error message returned from tfexec/errors.go doesn't include the name of the terraform variable that is causing the problem. This is because terraform attempts to make error messages fit the terminal width, which means error messages can have a newline character instead of a space depending on the length of the variable name, and therefore the error message regex in terraform-exec doesn't match properly. This PR fixes this behavior to correctly display error messages no matter the length of the terraform variable name by matching on "\s" instead of " ".
This issue doesn't appear to be a problem with the Terraform 0.11 regex because of how much shorter the error message is.
To …
> Support long terraform variable names in ErrMissingVar

- tfinstall/gitref/git_ref_test.go
As of https://github.com/hashicorp/terraform/commit/24d6c74e97430f4d0d78e879b487392fbf07914b, `master` on Core is now set to 0.15. Update tfinstall's git ref test to reflect this.
The `PR 25633` (https://github.com/hashicorp/terraform/pull/25633) test case started failing when the PR's branch was deleted 7 days ago. Since we can't predict when this will happen, I've removed the test case. I think we can be sure that if the other `refs/` cases work, PRs will too.
The commented-out test case `commit 83630a7` will be addressed in https://github.com/hashicorp/hcinstall/issues/1.
> Update git ref test

- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/state_mv_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/options.go
- tfexec/state_mv.go
- tfexec/state_mv_test.go
> add state mv

- tfexec/cmd.go
- tfexec/terraform.go
@kmoe i was adding prevention of usage of the CLI env vars and explored some convenience methods that may make usage of the `os.Environ` easier when desired.
Optionally, maybe we should just have a different method that uses `os.Environ` "cleanly", I'm not sure what the best UX is here, just trying it out as I had to make changes to how it looked up two types of prefixed env vars.
> Add environment variable helpers, prevent CLI env var usage

- go.mod
- go.sum
- tfexec/cmd.go
- tfexec/internal/e2etest/cmp.go
- tfexec/show.go
State values can contain numbers that are larger than `float64` can
precisely represent. `json.Unmarshal` when unmarshaled into an
`interface{}` uses `float64` to represent numbers by default. To
properly retain precision for numbers, we need to use a custom
`json.Decoder` with the `UseNumber()` method called on it, which will
use `json.Number` (a `string` alias) to store the numbers, preserving
their precision.
This does this at the `runTerraformCmdJSON` level, meaning anyone using that method with `v` as `interface{}` in the arguments will suddenly find that their `float64`s are now `json.Number`s, which may break them. The solution to this is to use the `Float64()` method on the `json.Number`, but it is a code change they will need to make.
> Use json.Number instead of float64 when parsing state.

- tfexec/apply.go
- tfexec/cmd.go
- tfexec/cmd_default.go
- tfexec/cmd_linux.go
- tfexec/destroy.go
- tfexec/errors.go
- tfexec/exit_errors.go
- tfexec/fmt.go
- tfexec/import.go
- tfexec/init.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/testdata/sleep/main.tf
- tfexec/output.go
- tfexec/plan.go
- tfexec/providers_schema.go
- tfexec/refresh.go
- tfexec/show.go
- tfexec/state_mv.go
- tfexec/terraform.go
- tfexec/upgrade012.go
- tfexec/validate.go
- tfexec/version.go
- tfexec/workspace_list.go
- tfexec/workspace_new.go
- tfexec/workspace_select.go
This potentially supersedes #91 
Probably best to review individual commits, the first commit splits exported errors to two files, one for exit error wrappers and one for the rest. No other changes beyond comments. The second commit adds the support for unwrapping and `errors.Is` comparisons.
> Better support for errors.Is and errors.As

- tfexec/internal/e2etest/util_test.go
This was missed in #116 but is needed for completeness.
> add automatic 0.14 testing

- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/testdata/bigint/main.tf
e2e test for https://github.com/hashicorp/terraform-exec/pull/113
Needs https://github.com/hashicorp/terraform-provider-random/pull/132.
> e2e test for bigint json.Number representation

- tfexec/init.go
- tfexec/init_test.go
- tfexec/internal/e2etest/import_test.go
- tfexec/internal/e2etest/version_test.go
- tfexec/terraform_test.go
- tfexec/version.go
From the Terraform 0.15 CHANGELOG:
* The `-lock` and `-lock-timeout` options are no longer available on `terraform init` [GH-27464]
* The `-verify-plugins=false` option is no longer available on `terraform init`. (Terraform now _always_ verifies plugins.) [GH-27461]
* The `-get-plugins=false` option is no longer available on `terraform init`. (Terraform now _always_ installs plugins.) [GH-27463]
This PR adds a compatibility error if the user attempts to set these options when using Terraform 0.15 and above. We maintain the existing behaviour of passing default values for these options prior to 0.15.
This fixes the errors seen in the nightly `master` test run ([example](https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/623/workflows/d5b12efb-9755-4833-ac5e-08bf51f6b381/jobs …
> Handle terraform init flags removed in 0.15

- tfexec/internal/e2etest/state_rm_test.go
- tfexec/state_rm.go
- tfexec/state_rm_test.go
Implemented the state remove command, with a lot of inspiration from the state move command
> Implemented state remove command

- .circleci/config.yml
Also:
-  Remove Slack notification step from Windows build jobs, because it doesn't work with the Windows build agent (known issue with CircleCI orb: https://github.com/CircleCI-Public/slack-orb/issues/208, https://github.com/CircleCI-Public/slack-orb/issues/217).
- Remove use of CircleCI contexts to import environment variables, due to change by Release Engineering.
The success notification has been tested.
> Notify on nightly success as well as failure

- tfexec/internal/e2etest/providers_schema_test.go
- tfexec/internal/e2etest/testdata/basic/main.tf
Version 3.1.0 of the null provider, released last Friday, changes some fields in the schema, which we read in the `TestProvidersSchema` e2e test. This PR updates them and fixes the provider version in the test config file.
This PR fixes the current nightly test failure.
> update null provider schema in tests

- .circleci/config.yml
- cmd/tfinstall/main.go
- tfexec/internal/e2etest/util_test.go
- tfinstall/gitref/git_ref.go
- tfinstall/gitref/git_ref_test.go
Terraform Core has renamed its main branch to `main`. Update references to that branch within terraform-exec, and rename our own branch to match.
> Update branch references

- .circleci/config.yml
This unblocks #135 and #139
It was confirmed by maintainer of https://github.com/terraform-providers/terraform-provider-oci that they will upgrade to 1.15 in the next couple of months and that they won't need to upgrade `tfexec`.
> ci: Drop support for Go 1.12

- tfexec/internal/e2etest/providers_schema_test.go
- tfexec/internal/e2etest/validate_test.go
This is to address some test failures caused by upstream 0.15 changes and (relatedly) the recent `terraform-json` bump https://github.com/hashicorp/terraform-exec/pull/143
> Update test data to reflect 0.15 changes

- tfexec/internal/e2etest/validate_test.go
As discussed elsewhere, versions such as `0.15.0-beta2` and `0.15.0-dev` do not satisfy the condition `tfv.GreaterThanOrEqual(version.Must(version.NewVersion("0.15.0")))`. A proposal will be made separately to `go-version` to provide prerelease-compatible comparison functions. In the meantime, hardcode the beta and nightly version numbers into the test so both tests pass.
> Fix validate test in 0.15 prereleases

- tfexec/version.go
- tfexec/version_test.go
Closes #13 
I didn't add more tests because it seemed like we'd be just testing mostly stdlib internals - either os.Exec or encoding/json. I'm open to ideas on what else to test though.
Also I think that exposing `VersionOutput` from the `Version()` method would be a good idea, but I avoided that just to retain compatibility, for now. Also it might be helpful to leverage (not yet published) library for parsing the provider addresses too. Either way I can open a separate issue for this.
> Parse version -json output and fall back to plaintext

- tfexec/internal/e2etest/providers_schema_test.go
This is to fix the following nightly failure:
```diff
- 	FormatVersion: "0.1",
+ 	FormatVersion: "0.2",
```
```
--- FAIL: TestProvidersSchema (1.30s)
--- FAIL: TestProvidersSchema/0_basic (0.89s)
--- FAIL: TestProvidersSchema/0_basic/basic-refs/heads/main (0.89s)
--- FAIL: TestProvidersSchema/1_empty_with_tf_file (0.40s)
--- FAIL: TestProvidersSchema/1_empty_with_tf_file/empty_with_tf_file-refs/heads/main (0.40s)
```
> hack: fix provider schema test in 0.15 prereleases

- tfexec/internal/e2etest/providers_schema_test.go
The first test was fixed, as expected, by https://github.com/hashicorp/terraform-exec/pull/148 but sadly I didn't notice there was a second subtest also affected by the same problem, so this patch is fixing it.
I expect that a better long-term solution will come once https://github.com/hashicorp/go-version/pull/85 is merged.
> fix (second) schema E2E test

- .circleci/config.yml
This is to address installation failure observed last night: https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/855/workflows/4f4a773f-e4d4-4991-8a0a-a075560601d1/jobs/11437
> circle: Run brew update before installing go

- tfexec/options.go
As of go-plugin v1.4.1, the reattach config now contains protocol version information so that protocol version can be negotiated during reattach. Please see https://github.com/hashicorp/go-plugin/pull/171.
> add ProtocolVersion to ReattachConfig

- tfexec/get.go
- tfexec/get_test.go
- tfexec/options.go
Generally it is possible and _probably common_ to use the `init` command to _initialize_ a Terraform module, which will install providers, setup remote state backend and download modules.
Sometimes it may be desirable to avoid installing providers, or initializing backends. I have one particular use case in tests for Terraform LS where I'd like to create a "mock module manifest" so that I can test some other functionality which relies on that module manifest, without having to copy around that module manifest statically. i.e. I'd like to generate "test data" programmatically via `tfexec.Get()`, but then mock out the rest of terraform commands.
I can't think of too many other use cases at this point, but the `get` command doesn't seem to be going anywhere [based on …
> Introduce tfexec.Get() for downloading modules

- tfexec/upgrade013.go
- tfexec/upgrade013_test.go
- tfexec/version.go
Closes #177
Let me know if I am missing something :)
> Add upgrade0.13 command

- .circleci/config.yml
Terraform recently introduced some code which requires Go 1.16
https://github.com/hashicorp/terraform/pull/28874
as can be seen from our failing acceptance tests:
```
internal/command/views/add.go:76:10: undefined: os.WriteFile
```
https://golang.org/pkg/os/#WriteFile
> Use Go 1.16 for building Terraform

- tfexec/exit_errors.go
I saw this error recently in LS CI
```
error: terraform core version not supported by configuration
```
and I think that we can make it more helpful this way.
```
error: terraform 1.1.0-dev not supported by configuration (~> 0.13 required)
```
> tfexec: Improve error message for incompatible version

- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/state_mv_test.go
- tfexec/internal/e2etest/state_rm_test.go
This is to reflect that JSON output changes are already shipped in `1.0.1`:
https://github.com/hashicorp/terraform/releases/tag/v1.0.1
> Fix Terraform version assumptions in test data

- tfexec/internal/e2etest/providers_lock_test.go
- tfexec/options.go
- tfexec/providers_lock.go
- tfexec/providers_lock_test.go
Adds feature requested in #201. This allows programatic generation of`.terraform.lock.hcl` files via this libary.
> Add `providers lock` Command

- scripts/release/release.sh
- use  `$(...)` over  ``` `...` ``` (backticks) because it is the legacy syntax required by only the very oldest of non-POSIX-compatible bourne-shells
- remove un-used `START_DIR` variable
- use `printf` bringing it up to date with the rest of the script and honors the `\n` without needing a `-e` flag.
> (maint) update scripts/release/release.sh

- tfexec/add.go
- tfexec/add_test.go
- tfexec/internal/testutil/tfcache.go
- tfexec/options.go
- tfexec/version.go
Fix #208 
Though the official release of the v1.1.0 is not shipped yet, while the alpha version is available. This means general users can use the `terraform add` feature already via the alpha CLI tool. As the `tfinstall` is able to install the alpha release, it means the `tfexec` users should also be able to use the alpha features (i.e. the `add`).
For the reason above, I've added a `Latest_v1_1_alpha` version for the test.
> add supports for cmd: terraform add

- tfexec/exit_errors.go
As of https://github.com/hashicorp/terraform/commit/89b05050ec0d1cae275fb9a3072e85364ba37a22 (https://github.com/hashicorp/terraform/pull/29469), Terraform Core now logs the following error when it detects that `terraform init` was required but not run:
```
Please run "terraform init".
```
In versions 0.13-1.0.5, this text reads instead "Error: could not load plugin".
This PR adds the new text to the regex.
Fixes nightly `main` test failure.
> Update ErrNoInit text

- tfexec/fmt.go
- tfexec/internal/e2etest/fmt_test.go
- tfexec/show.go
- tfexec/validate.go
- tfexec/version.go
- tfexec/workspace_list.go
This is a minor refactoring as a follow-up to a recently merged PR #209
> refactor: Replace `bytes.Buffer` with `strings.Builder`

- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/options.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/version.go
Closes #184 
https://www.terraform.io/docs/cli/commands/plan.html#replace-address
> The `-replace=...` option is available only from Terraform v0.15.2 onwards. For earlier versions, you can achieve a similar effect (with some caveats) using `terraform taint`.
> tfexec: Add support for Plan/Apply `Replace` option

- .circleci/config.yml
`winbuildtest` has been failing since 14th September with:
```
#!powershell.exe -ExecutionPolicy Bypass
choco install golang --version 1.16.4 --yes
Chocolatey v0.11.1
Installing the following packages:
golang
By installing, you accept licenses for the packages.
A newer version of golang (v1.17) is already installed.
Use --allow-downgrade or --force to attempt to install older versions, or use --side-by-side to allow multiple versions.
Chocolatey installed 0/1 packages. 1 packages failed.
See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
- golang - A newer version of golang (v1.17) is already installed.
Use --allow-downgrade or --force to attempt to install older versions, or use --side-by-side to allow multiple versions.
Exited with code exit status 1 …
```
> Fix Windows CI build

- tfexec/cmdstring.go
- tfexec/exit_errors.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/testdata/inmem-backend-locked/main.tf
Adds parsing for errors where Terraform fails to acquire a state lock. Returns a first-class `ErrStateLocked` error, including the corresponding `LockInfo`.  
Uses a slightly different [LockInfo structure](https://github.com/hashicorp/terraform/blob/a742d7ee8820f84afb1f0a3ec946b35ee5b26f84/internal/states/statemgr/locker.go#L187-L194) from upstream Terraform: 
* Excludes the `Info` section simply out of difficulty parsing out where that blurb ends
* Treats `Created` as a string instead of date, mostly because I wasn't sure how to handle the (unlikely) error from `time.Parse()` in `wrapExitError()`
_Side note:_ I don't see as much of a use-case for an `Unlock()` error, but I'm happy to add that in as well.
I've created a mini test-case here: https://play.golang.org/p/aAeRS5yOb7x. I can add …
> add error wrapping for locked state

- go.mod
- go.sum
- tfexec/internal/e2etest/providers_schema_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/internal/testutil/tfcache.go
I wanted to add tests for the new v1 format, but the [relevant PR](https://github.com/hashicorp/terraform/pull/29550) was not merged yet, so I just left a TODO in the appropriate places and the existing tests should fail when we bump `Latest_v1_1` - so we can cross the bridge when we get to it.
cc @alisdair
--- 
This brings in a bug fix for a panic: https://github.com/hashicorp/terraform-json/pull/44 which is the main motivation for the bump here.
--- 
I have prepared a draft PR https://github.com/hashicorp/terraform-exec/pull/226 with the necessary changes accounting for JSON format changes in TF 1.1.
> deps: Bump terraform-json to 0.13.0

- tfexec/exit_errors.go
This is to address the following nightly test failure:
```
util_test.go:113: [INFO] running Terraform command: /tmp/tfinstall756103370/gitref-refs-heads-main/terraform470134907 show -json -no-color
show_test.go:90: expected error ErrNoInit, got *fmt.wrapError: exit status 1
Error: Inconsistent dependency lock file
The following dependency selections recorded in the lock file are
inconsistent with the current configuration:
- provider registry.terraform.io/hashicorp/null: required by this configuration but no version is selected
To make the initial dependency selections that will initialize the dependency
lock file, run:
terraform init
--- FAIL: TestShow_errInitRequired (0.12s)
--- FAIL: TestShow_errInitRequired/basic-refs/heads/main (0.12s)
```
> fix: Account for upcoming init error message change

- tfexec/force_unlock.go
- tfexec/internal/e2etest/force_unlock_test.go
- tfexec/internal/e2etest/testdata/inmem-backend-locked/main.tf
Adds command for `terraform force-unlock -force LOCK_ID [DIR]`. Assumes the `-force` option as it's practically required in this context.
Regarding `forceUnlockDirArgMaxVersion`, the [command docs](https://www.terraform.io/docs/cli/commands/force-unlock.html) appear to indicate that the `[DIR]` positional argument is still valid but it was effectively removed around v0.15.0 in [this commit](https://github.com/hashicorp/terraform/commit/ca23a096d8c48544b9bfc6dbf13c66488f9b6964#diff-fa30e1342d858b292ab8a556b5a3bb7406ec8c744d11dbb267c1bda7cfee3df3L33-R34). Just wanted to clarify where that was coming from since it was failing `v0.15.x`+ test cases.
(Related to https://github.com/hashicorp/terraform-exec/issues/222)
> add command for force-unlock

- tfexec/internal/e2etest/workspace_test.go
- tfexec/version.go
- tfexec/workspace_show.go
- tfexec/workspace_show_test.go
This PR adds support for the `workspace show` command. 
Closes #239 
- [workspace show documentation](https://www.terraform.io/docs/cli/commands/workspace/show.html)
> Add support for the `workspace show` command

- .circleci/config.yml
We had E2E tests time out on `main` and in PRs recently:
https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/1334/workflows/d059b80e-43e4-4ea8-905f-165efaec939f/jobs/16081
https://app.circleci.com/pipelines/github/hashicorp/terraform-exec/1327/workflows/671e306a-746c-47d7-a14e-490b09c768e4/jobs/16037
Even when tests pass they get very close to the timeout, so this change aims to reduce the chance of the job timing out.
> circleci: bump timeout for E2E tests

- tfexec/internal/testutil/tfcache.go
Latest v1 is now v1.0.10, and latest v1.1.0 is v1.1.0-beta1.
> tests: bump to 1.0.10 and 1.1.0-beta1

- tfexec/graph.go
- tfexec/graph_test.go
- tfexec/internal/e2etest/graph_test.go
- tfexec/options.go
- tfexec/version.go
Implements the `graph` command for Terraform. At the moment, the output of the command is stored as just a string, but could potentially be loaded into an object that implements the DOT format.
> Implements the graph command

- tfexec/internal/e2etest/graph_test.go
- tfexec/internal/e2etest/providers_schema_test.go
This fixes failing E2E tests for the graph command.
> cmd/graph: Fix failing E2E tests

- README.md
- tfexec/cmd_default.go
- tfexec/internal/testutil/tfcache.go
All tests should pass except the known failure `TestShow_errNoInit` on main.
> bump v1 and v1.1 test versions

- CONTRIBUTING.md
- tfexec/internal/e2etest/providers_lock_test.go
Update CONTRIBUTING.md with some more helpful information on how to write tests, and correct one use of `runTestVersions()`.
> Clarify use of runTestVersions()

- go.mod
- tfexec/internal/e2etest/validate_test.go
This was only used in one place, and we don't need it.
Somewhat baffled as to why `go mod tidy` doesn't remove the `testify` lines from `go.sum`.
> tests: remove testify dependency

- go.mod
- tfexec/internal/e2etest/show_test.go
It was only being used for "pretty" text differences in 3 tests. It is still an indirect dependency due to hc-install.
```console
$ go mod why -m github.com/sergi/go-diff
github.com/hashicorp/terraform-exec/tfexec/internal/testutil
github.com/hashicorp/hc-install/build
github.com/go-git/go-git/v5
github.com/sergi/go-diff/diffmatchpatch
```
> deps: Remove direct dependency on github.com/sergi/go-diff

- go.mod
- go.sum
- tfexec/internal/e2etest/show_test.go
Replaced via trivial `strings` handling as the strings are not large.
> deps: Remove github.com/andybalholm/crlf

- tfexec/state_pull.go
- tfexec/state_pull_test.go
- tfexec/state_push.go
- tfexec/state_push_test.go
Adds support for `state pull` and `state push`
> Add support for state push/pull

- tfexec/state_pull_test.go
- tfexec/state_push_test.go
Merging #215 added back some more references to `testTempDir`, removed in https://github.com/hashicorp/terraform-exec/commit/eccad43b4c2e218b66878810bfbe89b8b117d392.
Merging this should fix tests on `main`.
> tests: fix missed testTempDir(t)

- tfexec/cmd.go
- tfexec/terraform.go
- tfexec/terraform_test.go
> tfexec: Add (Terraform).SetLog() method

- tfexec/destroy_test.go
- tfexec/fmt_test.go
- tfexec/get_test.go
- tfexec/graph_test.go
- tfexec/import_test.go
- tfexec/init_test.go
- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/testdata/bigint/main.tf
- tfexec/internal/e2etest/util_test.go
- tfexec/output_test.go
- tfexec/providers_lock_test.go
- tfexec/providers_schema_test.go
- tfexec/refresh_test.go
- tfexec/show_test.go
- tfexec/state_mv_test.go
- tfexec/state_rm_test.go
- tfexec/taint_test.go
- tfexec/terraform_test.go
- tfexec/untaint_test.go
- tfexec/upgrade012_test.go
- tfexec/upgrade013_test.go
- tfexec/version_test.go
- tfexec/workspace_delete_test.go
- tfexec/workspace_new_test.go
- tfexec/workspace_show_test.go
**Why?**
Prior to this patch, many tests would fail for the same reason - attempt to install older version of Terraform which isn't available for darwin/arm64.
For example:
```
--- FAIL: TestDestroyCmd (0.08s)
terraform_test.go:164: caching exec "v:0.12.31" in dir "/var/folders/9w/pddq2x656j76vxvsbhcs4nwr0000gq/T/tfinstall1718612104/v-0.12.31"
panic: error installing terraform "v:0.12.31": no ZIP archive found for terraform <nil> darwin/arm64 [recovered]
panic: error installing terraform "v:0.12.31": no ZIP archive found for terraform <nil> darwin/arm64
goroutine 99 [running]:
testing.tRunner.func1.2({0x102b2d280, 0x1400038cb80})
/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:1389 +0x1c8
testing.tRunner.func1()
/opt/homebrew/Cellar/go/1.18.1/libexec/src/testing/testing.go:13 …
```
> make tests pass (or skip) on darwin/arm64

- tfexec/cmd.go
- tfexec/cmd_default.go
- tfexec/cmd_default_test.go
- tfexec/cmd_linux.go
- tfexec/cmd_linux_test.go
- tfexec/internal/e2etest/errors_test.go
- tfexec/internal/e2etest/util_test.go
This PR intends to showcase the issue fixed by https://github.com/hashicorp/terraform-exec/pull/276:
- Commit 1-3: **all part of [#301](https://github.com/hashicorp/terraform-exec/pull/301)** (Sorry, I didn't realize becauseI forked, I couldn't create this PR off of my other branch)
- Commit 4: added a test which captures the issue; test fails
- Commit 5: cherry-picked commits from #276 that address the issue; test passes
**If the changes in #276 look good, can close this PR in favor of merging #276.** The tests added in this PR aren't very meaning and lose context once the fix is merged.
Currently, when runTerraformCmd is called, it starts a go-routine to kill the
Terraform CLI on context.Done(). However, when the Terraform CLI completes and
runTerraformCmd() finishes, the go-routine …
> Test for runTerraformCmd leaked go-routine

- .circleci/config.yml
This ensures that we don't reintroduce race conditions, which were recently addressed in https://github.com/hashicorp/terraform-exec/pull/299
`go test -race` tends to take longer than without the flag, so I also pre-emptively increased the timeout for the E2E test run.
> ci: Test with -race flag

- CONTRIBUTING.md
- README.md
- tfexec/internal/e2etest/util_test.go
If the env var `TFEXEC_E2ETEST_TERRAFORM_PATH` is set to the path of a valid local Terraform executable, when e2e tests are run, only tests appropriate to that executable's version will be run.
This involves both the `runTest()` and `runTestVersions()` codepaths, since both are used in e2e tests.
The code here is quite awkward due to the need to support multiple codepaths. Happy to refactor more if we prefer.
> Enable e2e testing against custom Terraform executable

- tfexec/state_push.go
- tfexec/state_push_test.go
_terrafrom state push command_ expect statefile path.
If it not specified it will fail with "Exactly one argument expected"
documentation link: https://www.terraform.io/cli/commands/state/push#usage
> Fix for state_push: path for statefile is reqired for run state push cmd

- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/testdata/cloud_backend/main.tf
- tfexec/internal/e2etest/testdata/remote_backend/main.tf
Reference: https://github.com/hashicorp/terraform/pull/31326
Fixes the new test failures against Terraform `main` branch. This also adds testing for the `cloud` and `remote` backends, which should be more stable as they are integral to the Terraform experience.
Previously:
```console
$ TFEXEC_E2ETEST_VERSIONS=refs/heads/main go test -count=1 -run='TestShow_noInitEtcdBackend' -v ./tfexec/internal/e2etest
=== RUN   TestShow_noInitEtcdBackend
=== RUN   TestShow_noInitEtcdBackend/etcd_backend-refs/heads/main
util_test.go:112: caching exec "gitref:refs/heads/main" in dir "/var/folders/w8/05f3x02n27x72g0mc2jy6_180000gp/T/tfinstall2067874872/gitref-refs-heads-main"
2022/06/30 15:56:57 git_revision.go:88: running terraform pre-clone check (timeout: 1m0s)
2022/06/30 15:56:57 git_revision.go:94: …
```
> tfexec/internal/e2etest: Skip TestShow_noInitEtcdBackend on >=1.3.0 and prereleases

- tfexec/cmd.go
- tfexec/cmd_test.go
- tfexec/terraform.go
- tfexec/terraform_test.go
Reference: https://github.com/hashicorp/terraform-plugin-sdk/issues/992
Closes #101
> tfexec: Add (Terraform).SetLogCore() and (Terraform).SetLogProvider() methods

- .circleci/config.yml
- tfexec/fmt_test.go
- tfexec/workspace_show_test.go
This PR now upgrades the macOS runner to the latest stable version of Xcode, v13.4.1, and removes two tests. This fixes the failing nightly build.
The two tests removed are:
- `TestFormat`
- This downloaded Terraform v0.7.6 and verified that running `Format()` resulted in a compatibility error, since `fmt` was only added in v0.7.7.
- Replaced with basic "defaults" tests and renamed to `TestFormatCmd`
- `TestWorkspaceShowCmd_v012`
- This downloaded Terraform v0.9.11 and verified that running `WorkspaceShow()` resulted in a compat error, since `workspace show` was only added in v0.10.0.
While we should be extremely reluctant to remove tests, in this case these tests were preventing us from testing all other Terraform behaviour on newer macOS environments (assuming we did not run two …
> ci: fix macos builds

- tfexec/init.go
- tfexec/init_test.go
- tfexec/terraform_test.go
This PR fixes unconfigurable force-copy, and change its default value to be false.
Fixes #262
> fix force-copy

- tfexec/force_unlock.go
This adds the `-no-color` flag by default to the `force-unlock` command.
Without this patch we can get `ForceUnlock` error:
```
exit status 1
[31mFailed to unlock state: Lock ID should be numerical value, got 'ID'[0m[0m
```
With this patch the error becomes:
```
exit status 1
Failed to unlock state: Lock ID should be numerical value, got 'ID'
```
(I purposefully ran `ForceUnlock` with an invalid argument here to have it error out)
> Run force-unlock with -no-color flag

- tfexec/exit_errors.go
- tfexec/terraform.go
Result of `go fmt ./...` with more recent Go version (1.19)
This is in preparation for CI changes which involve bumping Go.
> gofmt all the things!

- .github/workflows/nightly.yml
- .github/workflows/tests.yml
The intention is to raise a separate PR for the releasing workflow, once we address some remaining unknowns.
In the meantime, this will re-enable PR testing and nightly test runs, which we can feed into Slack again, now through the native GitHub/Slack integration.
The 3 test failures with `terraform` `refs/heads/main` are confirmed in https://github.com/hashicorp/hc-install/pull/86 and addressed in https://github.com/hashicorp/hc-install/pull/85 - which once merged will need to be brought in here by bumping `hc-install` as a dependency.
--- 
The fact that "unit tests" take ~2 minutes to finish on any platform make me question the filtering logic and/or the testing logic, but I will set that aside for another PR.
> ci: Run PR & nightly tests via GitHub Actions

- CHANGELOG.md
- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/destroy.go
- tfexec/destroy_test.go
- tfexec/internal/e2etest/apply_test.go
- tfexec/internal/e2etest/destroy_test.go
- tfexec/internal/e2etest/plan_test.go
- tfexec/internal/e2etest/refresh_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/refresh.go
- tfexec/refresh_test.go
- tfexec/version.go
> Adding ApplyJSON(), DestroyJSON(), PlanJSON() and RefreshJSON() functions

- tfexec/exit_errors.go
- tfexec/internal/e2etest/util_test.go
This is to address the nightly E2E test failures we've been seeing for some time now.
We _might_ be able to also address this more holistically as part of https://github.com/hashicorp/terraform-exec/pull/352 but this PR represents much smaller diff and still gets us back to green CI.
> fix: Update regex to reflect 1.4 error changes

- tfexec/internal/e2etest/apply_test.go
- tfexec/internal/e2etest/destroy_test.go
- tfexec/internal/e2etest/plan_test.go
- tfexec/internal/e2etest/refresh_test.go
- tfexec/internal/e2etest/show_test.go
- tfexec/internal/e2etest/upgrade012_test.go
- tfexec/internal/e2etest/util_test.go
When running e2e tests against a locally built Terraform binary set with `TFEXEC_E2ETEST_TERRAFORM_PATH`, the `runTestWithVersions` helper (introduced in #354) has some surprising behavior: it throws away the list of versions that was passed in and runs the test against the local binary instead. This seems fairly undesirable and was likely not an intended effect of that prior PR, since the tests using that helper are testing version-specific behavior (and thus are prone to fail when a local bin path is set!).
This PR proposes moving that version override behavior into `runTest`, where it was previously, and combining `runTestWithVersions` and `runTestVersions` into one test helper that runs the given test function against _only_ the versions passed in.
Closes …
> fix issues with version-specific tests when run against a local binary

- .github/workflows/release.yml
- CONTRIBUTING.md
- scripts/release/release.sh
- scripts/release/signore-wrapper.sh
This follows a guide in https://github.com/hashicorp/signore/blob/main/docs/SIGNING_GIT_COMMITS.md and https://github.com/hashicorp/signore/blob/main/docs/SIGNING_IN_CI.md
> ci: (re)enable releasing via GitHub Action workflow

- CONTRIBUTING.md
The `runTestVersions()` function has been effectively renamed to `runTestWithVersions()` and its behaviour modified by #354 ([e2etest/util_test.go]( https://github.com/hashicorp/terraform-exec/pull/354/files#diff-ea7385346bdbc5b135c051039bb1440eabf601dc7ff447a9a0d119a2f74d97df)) and #359 ([e2etest/util_test.go](https://github.com/hashicorp/terraform-exec/pull/359/files#diff-ea7385346bdbc5b135c051039bb1440eabf601dc7ff447a9a0d119a2f74d97df)) since the contributing docs were written.
Is CONTRIBUTING.md still correct?
> runTestWithVersions() in CONTRIBUTING.md

- .gitignore
- tfexec/internal/e2etest/metadata_functions_test.go
- tfexec/internal/e2etest/util_test.go
- tfexec/metadata_functions.go
- tfexec/metadata_functions_test.go
- tfexec/version.go
This PR adds support for the new `terraform metadata functions -json` command, which was introduced in https://github.com/hashicorp/terraform/pull/32487. We need this to obtain the function signatures within terraform-ls.
Depends on:
* https://github.com/hashicorp/terraform-json/pull/68
> Add support for `metadata functions -json` command

- scripts/release/release.sh
Note that GHA's `GITHUB_REF` is the whole refspec, not just the branch name, which should still work according to the man page.
> scripts/release: update env var for GHA

- .github/workflows/release.yml
Since we have branch protection enabled and we need to push new commit as part of the release into the protected branch (`main`), we run into some limitations as far as how this can be handled in GitHub Actions.
- workflow tokens cannot bypass the branch protection, as per https://github.com/community/community/discussions/13836
- Deploy keys with write permissions can - as these have similar scope as admin users on the repo as per [official docs](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys)
> Deploy keys with write access can perform the same actions as an organization member with admin access, or a collaborator on a personal repository.
I have already generated the deploy key and added to the repo + added the private part as a …
> ci: Use deploy SSH key to push

- .github/workflows/release.yml
Should address https://github.com/hashicorp/terraform-exec/actions/runs/4224637608/jobs/7335853270#step:4:20
> ci: add forgotten mkdir to release workflow

- scripts/release/release.sh
During the release workflow https://github.com/hashicorp/terraform-exec/actions/runs/4224742942/jobs/7336093882, the target version could not be parsed from the changelog, due to a typo.
The release script should have exited with an error at this point, but instead continued with a blank `TARGET_VERSION`, causing problems down the line.
This PR makes release.sh exit 1 if the version cannot be parsed from the changelog.
The previous behaviour was not explicit due to overuse of subshells. This change makes it more explicit.
Tested the behaviour when CHANGELOG.md is valid:
```sh
$ ./scripts/release/release.sh
...
$ echo $?
0
```
Modified CHANGELOG.md so the first line said "unreleased" instead of "Unreleased".
```sh
$ ./scripts/release/release.sh
Target version not found in changelog, …
```
> scripts/release: error when version cannot be parsed

- tfexec/cmd_default.go
- tfexec/cmd_linux.go
- tfexec/internal/e2etest/errors_test.go
https://github.com/hashicorp/terraform-exec/pull/352 introduced a bug in which stderr from Terraform commands was not included in the error returned from `tf.Apply()`, etc.
This PR fixes this. Note the inclusion of `errBuf` where `tf.wrapExitError()` was used before.
Also add a test step that fails before this change.
> bugfix: correctly populate stderr

- .github/workflows/tests.yml
Depends on
- https://github.com/hashicorp/terraform-exec/pull/378
- https://github.com/hashicorp/terraform-exec/pull/357
--- 
This is a follow-up to https://github.com/hashicorp/terraform-exec/pull/357 to ensure we don't introduce new files with missing copyright headers and keep the repository compliant.
> ci: Add PR test for copyright headers

- tfexec/cmd.go
- tfexec/cmd_test.go
Setting the environment variable to an empty string confuses the terraform binary as seen below:
```
TF_WORKSPACE= terraform init -no-color -input=false -get=false -upgrade=false -backend=false
Error: Terraform Cloud returned an unexpected error
invalid value for workspace
```
With this patch the `TF_WORKSPACE` will not exist and avoids the above problem. I have tested this locally with terraform 1.4.5 and it works.
> remove workspace env var and not set it to an empty string.

- tfexec/internal/e2etest/test_test.go
- tfexec/internal/e2etest/testdata/test_command_failing/main.tf
- tfexec/internal/e2etest/testdata/test_command_failing/tests/passthrough.tftest
- tfexec/internal/e2etest/testdata/test_command_passing/main.tf
- tfexec/internal/e2etest/testdata/test_command_passing/tests/passthrough.tftest
- tfexec/internal/testutil/tfcache.go
- tfexec/options.go
- tfexec/test.go
- tfexec/test_test.go
- tfexec/version.go
Closes #398
Reference: https://github.com/hashicorp/terraform/pull/33454
Adds support for the `terraform test` command, which currently supports JSON machine-readable output and one flag for configuring the tests directory away from the command default of `tests`. The command will return a non-zero status if any of the tests fail, which returns an error back to callers of the `Test` function. If consumers need access to the pass/fail test results, the terraform-json Go module will need to be enhanced to support the test summary JSON, e.g.
```
{"@level":"info","@message":"Failure! 0 passed, 1 failed.","@module":"terraform.ui","@timestamp":"2023-07-25T10:03:42.980799-04:00","test_summary":{"status":"fail","passed":0,"failed":1,"errored":0,"skipped":0},"type":"test_summary"}
```
Output of …
> tfexec: Initial test command support

- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/internal/e2etest/apply_test.go
Implement the ApplyOption interface for the DestroyFlagOption
struct which enables the user to run `terraform apply -destroy`
as they would using the terraform binary directly by calling
`func (tf *Terraform) Apply`.
> apply: allow use of -destroy flag for compatible terraform versions

- CHANGELOG.md
- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/options.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/version.go
Added support for `-refresh-only` flag for both `Plan` and `Apply` methods.
> feat: add refresh-only flag for plan and apply methods

- .github/dependabot.yml
This disables dependabot for GHA to avoid conflicts with our own internal tooling, which comes with an added layer of trusted/reviewed revisions.
> github: Replace dependabot with internal tooling

- go.mod
- go.sum
- tfexec/internal/e2etest/cmp.go
- tfexec/internal/e2etest/show_test.go
- tfexec/options.go
- tfexec/show.go
> Add ShowOption for configuring JSON decoding

- .github/workflows/tests.yml
- CHANGELOG.md
- tfexec/apply.go
- tfexec/apply_test.go
- tfexec/force_unlock_test.go
- tfexec/internal/testutil/tfcache.go
- tfexec/options.go
- tfexec/plan.go
- tfexec/plan_test.go
- tfexec/version.go
- tfexec/version_test.go
This PR introduces a new plan and apply flag `-allow-deferral`. This flag enables the deferred actions experiment that was introduced in Terraform [`v1.9.0-alpha20240404`](https://github.com/hashicorp/terraform/releases/tag/v1.9.0-alpha20240404)
- I wasn't sure if there was an _external_ interface for checking that experiments are enabled from the Terraform CLI, so I just check for `alpha` or `dev` in the version as a best effort. Happy to update with a more accurate method if one exists!
> tfexec: Add `-allow-deferral` experimental options to `Plan` and `Apply` commands

- catalog-info.yaml
Includes basic metadata for registering terraform-exec as a library component in our internal Backstage installation. See DW-481.
> Add a catalog-info.yaml file for Backstage

- README.md
We recommend practitioners to use the framework for new provider development because it offers significant advantages as compared to the SDKv2.
> docs: reference the plugin framework

- README.md
After #499 was merged, I suppose this reference in the readme needs to be updated as well
> Update reference to Go version

- README.md
- go.mod
This is to unblock https://github.com/hashicorp/terraform-exec/pull/507
> go: bump version to 1.23/1.24

- tfexec/internal/e2etest/query_test.go
- tfexec/internal/e2etest/testdata/query/main.tf
- tfexec/internal/e2etest/testdata/query/main.tfquery.hcl
- tfexec/internal/testutil/tfcache.go
- tfexec/options.go
- tfexec/query.go
- tfexec/query_test.go
- tfexec/version.go
Fixes https://hashicorp.atlassian.net/browse/TF-27483
This PR targets the [pre-release](https://github.com/hashicorp/terraform-exec/tree/pre-release) branch instead of [main](https://github.com/hashicorp/terraform-exec/tree/main), so we can keep this unreleased until the Terraform 1.14 beta version is published.
This PR adds support for executing the new `terraform query` command.
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
> Add support for `query` subcommand

- go.mod
- go.sum
- tfexec/cmd.go
- tfexec/internal/e2etest/query_test.go
- tfexec/internal/e2etest/testdata/query/main.tf
- tfexec/internal/e2etest/testdata/query/main.tfquery.hcl
- tfexec/internal/testutil/tfcache.go
- tfexec/options.go
- tfexec/query.go
- tfexec/query_test.go
- tfexec/version.go
This PR adds a new internal method that allows easier consumption of Terraform's structured log format. It exposes log messages as an iterator via `iter.Seq[NextMessage]`.
`QueryJSON` is the first command that makes use of new the method.
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
> Implement `QueryJSON` and introduce new way for consuming Terraform's structured logging

- CHANGELOG.md
Prepare changelog for 0.24.0 release
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
> Prepare changelog for 0.24.0 release
